Gas optimizations
amun/CMTAT pull request #1
Opened 2023-05-23 09:20 UTC by mariogutval

Mandatory:

- [x] Remove initializations to default values
- [x] Uncheck index variable increment in for-loops
- [x] Use calldata instead of memory wherever is possible
- [ ] Check require strings length

Optional:

- [ ] Substitute require statements with custom errors

2023-05-23 11:27 UTC, diego-G requested changes

2023-05-23 11:27 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
>          uint256 mostRecent = 0;
Missing here.

2023-05-30 10:50 UTC, diego-G requested changes
Minimal changes.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(time > block.timestamp)) revert SnapshotScheduledInThePast(time, block.timestamp);
Easier to read `if(time <= block.timestamp)`

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +            if(!(time > _scheduledSnapshots[_scheduledSnapshots.length - 1])) {
Same as above.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(time > block.timestamp)) revert SnapshotScheduledInThePast(time, block.timestamp);
Same as above.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(oldTime > block.timestamp)) revert SnapshotAlreadyDone();
Same.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(newTime > block.timestamp)) revert SnapshotScheduledInThePast(newTime, block.timestamp);
Same.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +            if(!(newTime > _scheduledSnapshots[index - 1])) revert SnapshotTimestampBeforePreviousSnapshot(newTime, _scheduledSnapshots[index - 1]);
Same.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(time > block.timestamp)) revert SnapshotAlreadyDone();
Same.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(time > block.timestamp)) revert SnapshotAlreadyDone();
Same.

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/wrapper/optional/ValidationModule.sol
> +        if(ruleEngine == ruleEngine_) revert SameValue();
Why not `_ruleEngine` ?

2023-05-30 10:50 UTC, diego-G commented on contracts/modules/security/AuthorizationModule.sol
> +        if(admin == address(0)) revert InvalidAddress();
Rename the error to `AddressZeroNotAllowed`.

2023-05-30 10:50 UTC, diego-G commented on contracts/libraries/Errors.sol
> +error NoScheduledSnapshot();
Rename to `SnapshotNotScheduled` to follow pattern.

2023-05-30 10:50 UTC, diego-G commented on contracts/libraries/Errors.sol
> +error NotLastSnapshot();
Rename to `SnapshotNeverScheduled`.

2023-05-30 10:50 UTC, diego-G commented on contracts/libraries/Errors.sol
> +error SetRuleEngine(address ruleEngine);
This error is never used. Please, remove it.

2023-05-30 10:50 UTC, diego-G commented on contracts/libraries/Errors.sol
> +error Allowance(uint256 allowance, uint256 currentAllowance);
Rename to `WrongAllowance`.

2023-05-30 10:50 UTC, diego-G commented on contracts/libraries/Errors.sol
> +error BeforeTokenTransfer(address from, address to, uint256 amount);
Rename to `InvalidTransfer`.

2023-05-30 15:42 UTC, mariogutval commented on contracts/modules/wrapper/optional/ValidationModule.sol
> +        if(ruleEngine == ruleEngine_) revert SameValue();
I just let it as it was

2023-05-30 16:07 UTC, mariogutval commented on contracts/modules/internal/SnapshotModuleInternal.sol
> +        if(!(time > block.timestamp)) revert SnapshotScheduledInThePast(time, block.timestamp);
There is no gas optimization, so I'll use your way, which is more readable

2023-05-31 08:13 UTC, diego-G approved these changes

2023-05-31 08:14 UTC, merged