refactor: 🪖 migrate from truffle to hardhat
amun/CMTAT pull request #16
Opened 2023-12-01 05:55 UTC by zarifpour

- Remove truffle-config.js
- Remove migrations/1_deploy_contracts.js
- Add scripts/1_deploy_contracts.js
- Update hardhat.config.js with network configurations 
- Update ESLint configuration, environment, and globals Update devDependencies in package.json
- Update deployment.test.js with new deployment logic Update .env.example with private key and node URLs

2023-12-01 18:39 UTC, zarifpour commented
Sample of deployments (x2): https://goerli.etherscan.io/address/0x1e874187bef4b3bc59a906b5838a6f3ea849bb6f

<details>
  <summary>console logs</summary>

```
❯ npx hardhat run scripts/1_deploy_contracts.js --network goerli

+=================================+
|  Deploying CMTAT_BASE Contract  |
+=================================+

Deployed contract object:
 BaseContract {
  target: '0xb49f2585541cCaEc347F1B1Aa318027fCfEbdffc',
  interface: Interface {
    fragments: [
      [ConstructorFragment], [ErrorFragment],    [ErrorFragment],
      [ErrorFragment],       [EventFragment],    [EventFragment],
      [EventFragment],       [EventFragment],    [EventFragment],
      [EventFragment],       [EventFragment],    [EventFragment],
      [EventFragment],       [EventFragment],    [EventFragment],
      [EventFragment],       [EventFragment],    [EventFragment],
      [EventFragment],       [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment],
      [FunctionFragment],    [FunctionFragment], [FunctionFragment]
    ],
    deploy: ConstructorFragment {
      type: 'constructor',
      inputs: [],
      payable: false,
      gas: null
    },
    fallback: null,
    receive: false
  },
  runner: HardhatEthersSigner {
    _gasLimit: undefined,
    address: '0x1E874187BeF4b3BC59A906B5838A6f3Ea849bB6f',
    provider: HardhatEthersProvider {
      _hardhatProvider: [LazyInitializationProviderAdapter],
      _networkName: 'goerli',
      _blockListeners: [],
      _transactionHashListeners: Map(0) {},
      _eventListeners: []
    }
  },
  filters: {},
  fallback: null,
  deploymentTransaction: [Function (anonymous)],
  [Symbol(_ethersInternal_contract)]: {}
}
Proxy deployed at: 0xb49f2585541cCaEc347F1B1Aa318027fCfEbdffc

Waiting 30 seconds for the network to propagate...

+============================+
|  Verifying Proxy Contract  |
+============================+

Proxy contract address: 0xb49f2585541cCaEc347F1B1Aa318027fCfEbdffc

Verifying contract on explorer...
The contract 0xb49f2585541cCaEc347F1B1Aa318027fCfEbdffc has already been verified
Verification submitted for contract at address: 0xb49f2585541cCaEc347F1B1Aa318027fCfEbdffc

+==================================+
|  Verifying Proxy Admin Contract  |
+==================================+

Proxy Admin contract address: 0x8fD118Fd02A27a31BA824bCA304F26060Bc4bDC8

Verifying contract on explorer...
The contract 0x8fD118Fd02A27a31BA824bCA304F26060Bc4bDC8 has already been verified
Verification submitted for contract at address: 0x8fD118Fd02A27a31BA824bCA304F26060Bc4bDC8

+=====================================+
|  Verifying Implementation Contract  |
+=====================================+

Implementation contract address: 0x3F3161F82894C71874D26d3322AfD3394279eb04

Verifying contract on explorer...
The contract 0x3F3161F82894C71874D26d3322AfD3394279eb04 has already been verified
Verification submitted for contract at address: 0x3F3161F82894C71874D26d3322AfD3394279eb04

+======================+
|  Deployment Summary  |
+======================+

Deployed Proxy Contract Address: 0xb49f2585541cCaEc347F1B1Aa318027fCfEbdffc
Proxy Admin Contract Address: 0x8fD118Fd02A27a31BA824bCA304F26060Bc4bDC8
Implementation Contract Address: 0x3F3161F82894C71874D26d3322AfD3394279eb04
```
</details>

2023-12-01 18:53 UTC, zarifpour commented
I suggest creating a new branch and merging to it, i.e. `wrapped-assest-hh`, to preserve our truffle codebase just in case. We can experiment there and decide if we would like to do a complete migration.

2023-12-05 10:19 UTC, diego-G requested changes
Minimal changes

2023-12-05 10:19 UTC, diego-G commented on scripts/1_deploy_contracts.js
> +  await performVerification(() => verifyProxyAdminContract(proxyContract), 'Proxy Admin')
Add an `if` statement when the ProxyAdmin and implementation were not deployed and therefore are already verified.

2023-12-05 21:34 UTC, zarifpour commented on scripts/1_deploy_contracts.js
> +  await performVerification(() => verifyProxyAdminContract(proxyContract), 'Proxy Admin')
this should be okay because it is a try catch

2023-12-05 21:35 UTC, zarifpour commented on hardhat.config.js
> +require('@nomiclabs/hardhat-etherscan')
this was deprecated... need to move to hardhat-verify

2023-12-06 14:26 UTC, diego-G approved these changes, later dismissed

2023-12-06 15:49 UTC, mariogutval approved these changes, later dismissed

2023-12-07 10:22 UTC, diego-G commented
I've just realised that we still have truffle in several package scripts, `usage.md` and `toolchain.md` files. Please @zarifpour, replace it by Hardhat.

2023-12-08 18:06 UTC, zarifpour commented
Please review the last commit

2023-12-11 13:23 UTC, diego-G approved these changes

2023-12-11 13:23 UTC, merged