feat(holesky): deploy test cmtat
amun/CMTAT pull request #23
Opened 2024-02-02 18:00 UTC by zarifpour

```
+==================================+
|  Verifying Proxy Admin Contract  |
+==================================+

Proxy Admin contract address: 0x033cc0Fd48ECE2364EFfce9745Af055D0B8A339A 

Verifying contract on explorer...
The contract 0x033cc0Fd48ECE2364EFfce9745Af055D0B8A339A has already been verified on Etherscan.
https://holesky.etherscan.io/address/0x033cc0Fd48ECE2364EFfce9745Af055D0B8A339A#code
Verification submitted for contract at address: 0x033cc0Fd48ECE2364EFfce9745Af055D0B8A339A
Proxy Admin contract verified successfully.

+=====================================+
|  Verifying Implementation Contract  |
+=====================================+

Implementation contract address: 0x73225F88fEEA4E41Fc67E986a95AC61dd7118866 

Verifying contract on explorer...
Successfully submitted source code for contract
contracts/modules/CMTAT_BASE.sol:CMTAT_BASE at 0x73225F88fEEA4E41Fc67E986a95AC61dd7118866
for verification on the block explorer. Waiting for verification result...

Successfully verified contract CMTAT_BASE on the block explorer.
https://holesky.etherscan.io/address/0x73225F88fEEA4E41Fc67E986a95AC61dd7118866#code

Verification submitted for contract at address: 0x73225F88fEEA4E41Fc67E986a95AC61dd7118866
Implementation contract verified successfully.

+======================+
|  Deployment Summary  |
+======================+

Deployed Proxy Contract Address: 0xd8d42193150763b51a8C5bD1F372Cb0e6A75DCf9
Proxy Admin Contract Address: 0x033cc0Fd48ECE2364EFfce9745Af055D0B8A339A
Implementation Contract Address: 0x73225F88fEEA4E41Fc67E986a95AC61dd7118866
```

2024-02-06 10:57 UTC, diego-G requested changes

2024-02-06 10:57 UTC, diego-G commented on .env.example
>  GOERLI_NODE=""
Let's remove GOERLI references.

2024-02-06 10:57 UTC, diego-G commented on .openzeppelin/unknown-17000.json
> +{
Shall we remove now *1337.json file?

2024-02-06 10:57 UTC, diego-G commented on hardhat.config.js
>        goerli: process.env.ETHERSCAN_API_KEY,
Remove goerli everywhere please.

2024-02-06 17:31 UTC, mariogutval commented on .openzeppelin/unknown-17000.json
> +{
I think we should add it to .gitignore. It's going to appear every time we simulate a deployment locally.

2024-02-06 17:32 UTC, mariogutval requested changes

2024-02-06 17:32 UTC, mariogutval commented on .env.example
>  GOERLI_NODE=""
Agree

2024-02-06 17:32 UTC, mariogutval commented on hardhat.config.js
>      //   accounts: [process.env.PRIVATE_KEY],
Should we also remove `mumbai`?

2024-02-06 18:25 UTC, zarifpour commented on .openzeppelin/unknown-17000.json
> +{
done, removed and added to .gitignore

2024-02-06 18:25 UTC, zarifpour commented on hardhat.config.js
>      //   accounts: [process.env.PRIVATE_KEY],
removed

2024-02-07 10:15 UTC, diego-G approved these changes

2024-02-07 10:49 UTC, mariogutval approved these changes

2024-02-07 10:50 UTC, merged