Cleanup
amun/CMTAT pull request #3
Opened 2023-05-31 11:14 UTC by diego-G

- [x] Remove CMTAT standalone
- [x] Remove Enforcement mandatory module
- [x] Remove Snapshot optional non-audited module
- [x] Remove Killswitch
- [x] Remove OnlyDelegateCall security module
- [x] Remove MetaTx optional module
- [x] Remove Debt optional modules
- [x] Remove Validation optional module

Close #AM-1320

2023-05-31 15:12 UTC, CarsonBrown96 commented
LGTM

2023-05-31 15:12 UTC, CarsonBrown96 approved these changes

2023-05-31 15:27 UTC, mariogutval requested changes

2023-05-31 15:27 UTC, mariogutval commented on truffle-config.js
> +      network_id: 5777 // match any network
```suggestion
      network_id: 5777
```

2023-05-31 15:27 UTC, mariogutval commented on truffle-config.js
> +      network_id: 5777 // Ethereum public network
```suggestion
      network_id: 5777
```

2023-05-31 15:27 UTC, mariogutval commented on truffle-config.js
> +          runs: 200
I think we should test several values to try to find the optimal one

2023-06-01 08:17 UTC, mariogutval approved these changes

2023-06-01 08:18 UTC, merged