feature/downgrade_hardhat_upgrades
amun/CMTAT pull request #32
Opened 2024-07-01 15:40 UTC by zarifpour

2024-07-02 13:12 UTC, diego-G requested changes
Please, get Holesky metadata back https://github.com/amun/CMTAT/blob/908e608a71b55b569aba696d95392b8e67bb3a8a/.openzeppelin/unknown-1337.json. 

Rest LGTM

2024-07-05 10:44 UTC, diego-G approved these changes

2024-07-05 10:45 UTC, diego-G approved these changes

2024-07-05 13:31 UTC, JPMora89 commented
LGTM contracts match with the ones in Tenderly

2024-07-05 13:32 UTC, JPMora89 approved these changes
LGTM hardhat versions downgraded

2024-07-05 13:38 UTC, merged